version: '3.1'
services:
  dtdevss-truco-fe:
    container_name: truco-fe
    image: dtdevss/truco-fe
    env_file:
      - .env.production
    restart: 'always'
    network_mode: 'host'
    build: .
