image: docker:19.03.12
services:
  - docker:19.03.12-dind

stages:
  - buildfront
  - deploy

variables:
  CONTAINER_FRONT_IMAGE: $CI_REGISTRY_IMAGE:frontend

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY


Building frontend:
  stage: buildfront
  script:
    - docker build -t $CONTAINER_FRONT_IMAGE ./
    - docker push $CONTAINER_FRONT_IMAGE

deploy:
  stage: deploy
  image: ubuntu
  before_script:
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client git -y )'
  - eval $(ssh-agent -s)
  - echo "$SSH_PEM" | tr -d '\r' | ssh-add -
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - ssh-keyscan $SSH_HOST >> ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts
  script:
  - ssh $SSH_USER@$SSH_HOST "docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY;docker rmi $CONTAINER_FRONT_IMAGE;docker rmi $CONTAINER_FRONT_IMAGE:latest;docker rmi $CONTAINER_FRONT_IMAGE:frontend;docker pull $CONTAINER_FRONT_IMAGE;docker stop frontend;docker rm frontend;docker run --name frontend -d -t --network="host" $CONTAINER_FRONT_IMAGE"
  only:
    - master