export const cards = [
  { nr: 'A', suit: 'h' },
  { nr: '2', suit: 'h' },
  { nr: '3', suit: 'h' },
  { nr: '4', suit: 'h' },
  { nr: '5', suit: 'h' },
  { nr: '6', suit: 'h' },
  { nr: '7', suit: 'h' },
  { nr: 'Q', suit: 'h' },
  { nr: 'J', suit: 'h' },
  { nr: 'K', suit: 'h' },
  { nr: 'A', suit: 'd' },
  { nr: '2', suit: 'd' },
  { nr: '3', suit: 'd' },
  { nr: '4', suit: 'd' },
  { nr: '5', suit: 'd' },
  { nr: '6', suit: 'd' },
  { nr: '7', suit: 'd' },
  { nr: 'Q', suit: 'd' },
  { nr: 'J', suit: 'd' },
  { nr: 'K', suit: 'd' },
  { nr: 'A', suit: 'c' },
  { nr: '2', suit: 'c' },
  { nr: '3', suit: 'c' },
  { nr: '4', suit: 'c' },
  { nr: '5', suit: 'c' },
  { nr: '6', suit: 'c' },
  { nr: '7', suit: 'c' },
  { nr: 'Q', suit: 'c' },
  { nr: 'J', suit: 'c' },
  { nr: 'K', suit: 'c' },
  { nr: 'A', suit: 's' },
  { nr: '2', suit: 's' },
  { nr: '3', suit: 's' },
  { nr: '4', suit: 's' },
  { nr: '5', suit: 's' },
  { nr: '6', suit: 's' },
  { nr: '7', suit: 's' },
  { nr: 'Q', suit: 's' },
  { nr: 'J', suit: 's' },
  { nr: 'K', suit: 's' },
];

exports.cards = cards;
